version: 2.1
jobs:
  install_and_test:
    docker:
      - image: archlinux/base
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pacman -Sy --noconfirm base-devel libime python-pip
            pip install opencc pypinyin setuptools pytest pytest-cov coverage
            python setup.py install
      - run:
          name: Run tests
          command: |
            bash utils/test.sh
workflows:
  version: 2
  test:
    jobs:
      - install_and_test
