on:
  workflow_dispatch: {}
  schedule:
    - cron: "37 20 14 * *"

jobs:
  trigger-bnp:
    name: Trigger build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build_dict.yml",
              ref: 'pkg-moegirl'
            })
